ybind/urls.py
from django.contrib import admin
from django.urls import path, re_path

from dns.views import zone
from dns.views import details
from rbac import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.Login.as_view()),
    path('zone-list/', zone.Zone.as_view(), name="zone-list"),
    re_path('^zone-add/(?P<id>\d+)/$', zone.ZoneAdd.as_view()),
    re_path('^zone-add/', zone.ZoneAdd.as_view(), name="zone-add"),
    re_path(r'^$', zone.Zone.as_view()),
    re_path(r'^detail/(?P<domain>.+)/$', details.Details.as_view()),
    re_path(r'^detail-add/(?P<domain>.+)/$', details.DetailAdd.as_view()),
    re_path(r'^batch-add/$', details.BatchAdd.as_view(), name="batch-add"),
]

dns/models.py
from django.db import models
# Create your models here.


class Records(models.Model):
    id = models.AutoField(primary_key=True)
    zone = models.CharField(max_length=255,verbose_name="属于哪个Zone")
    host = models.CharField(max_length=255,verbose_name="二级域名")
    # dns_type = ((0,"A"),(1,"MX"),(2,"CNAME"),(3,"TXT"),(4,"NS"),(5,"SOA"),(6,"AAAA"),(7,"PTR"),)
    # type = models.SmallIntegerField(choices=dns_type,default=0,verbose_name="DNS类型")
    dns_type = models.CharField(max_length=16,null=True,verbose_name="DNS类型")
    data = models.CharField(max_length=255,verbose_name="对应的IP/值")
    ttl = models.IntegerField(default=60,verbose_name="生存周期时间")
    mx_priority = models.IntegerField(default=None)
    dns_view = ((0,"Telecom"),(1,'Unicom'),(2,"CMCC"),(3,"other"))
    view = models.SmallIntegerField(choices=dns_view,default=3,verbose_name="属于哪个公司")
    priority = models.IntegerField(default=255)
    refresh = models.IntegerField(default=28800)
    retry = models.IntegerField(default=14400)
    expire = models.IntegerField(default=86400)
    minimum = models.IntegerField(default=86400)
    serial = models.IntegerField(default=0)
    resp_person = models.CharField(max_length=64,default="test.com")
    primary_ns = models.CharField(max_length=64,default="ns.test.com.")

class ZoneRecords(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255,verbose_name="属于哪个Zone",default="abc.com")

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html">
    <meta charset="utf-8">
{#    <meta http-equiv="X-UA-Compatible" content="IE=edge">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1">#}

    <title> 智能DNS管理系统 Z-Bind  </title>
    <style type = "text/css">
    .Validform_right{color:green}
    .Validform_wrong{color:red}
    </style>
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'css/nprogress.css' %}" rel="stylesheet">
    <!-- iCheck -->
    <link href="{% static 'css/green.css' %}" rel="stylesheet">
    <!-- bootstrap-progressbar -->
    <link href="{% static 'css/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet">
    <!-- JQVMap -->
    <link href="{% static 'css/jqvmap.min.css' %}" rel="stylesheet"/>
    <!-- bootstrap-daterangepicker -->
    <link href="{% static 'css/daterangepicker.css' %}" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="{% static 'css/custom.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/sweetalert.css' %}" rel="stylesheet">
    <link href="{% static 'css/select2.css' %}" rel="stylesheet">
    <link href="{% static 'chosen/css/chosen-bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'chosen/css/chosen.min.css' %}" rel="stylesheet">

  </head>

  <body class="nav-md">

    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="index.html" class="site_title">
			  <span>  智能DNS管理系统     </span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <div class="profile clearfix">
              <div class="profile_pic">
                <img src="/static/images/img.jpg" alt="..." class="img-circle profile_img">
              </div>
              <div class="profile_info">
                <span>Welcome,</span>
                    {% if user.is_authenticated %}
                        <h2>{{ user.username }}</h2>
                    {% else %}
                        admin
                    {% endif %}
              </div>
            </div>
            <!-- /menu profile quick info -->

            <br />

			
            <!-- 菜单 -->
           <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <ul class="nav side-menu">
                  <li><a href="{% url 'zone-list' %}"><i class="fa fa-home"></i> 域名列表 <span class="fa fa-chevron-right"></span></a>
{#                    <ul class="nav child_menu">#}
{#                        <li><a href="1">Dashboard</a></li>#}
{#                    </ul>#}
                  </li>
                  </li>
				  
                  <li><a href="{% url 'zone-add' %}"><i class="fa fa-group"></i> 域名添加 <span class="fa fa-chevron-right"></span></a>
{#                    <ul class="nav child_menu">#}
{#                              <li><a >批量添加域名</a></li>#}
{#                    </ul>#}
                  </li>


				<li><a href="{% url 'batch-add' %}"><i class="fa fa-star-half"></i>批量管理 <span class="fa fa-chevron-right"></span></a>
{#                    <ul class="nav child_menu">#}
{#                                   <li><a href="{% url 'zone-list' %}">域名列表</a></li>#}
{#                                   <li><a href="{% url 'zone-add' %}">批量添加</a></li>#}
{#                     </ul>#}
                  </li>


                </ul>
              </div>
			 <!-- /菜单 -->
			 

         </div>

            <!-- 工具条菜单 -->
            <div class="sidebar-footer hidden-small">
              <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Logout" href="111">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              </a>
            </div>

          </div>
        </div>

        <!-- 顶部导航 -->
        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="" >
                  <li><a href="zz"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
              </ul>


            </nav>
          </div>
        </div>
        <!-- /top navigation -->
        <!-- /顶部导航 -->
		
		

		<!-- 网页内容 -->

		<div class="right_col" role="main">
		  {% block content %}
		  {% endblock %}



          {% block body %}
          {% endblock %}
		 <!-- 网页内容 -->
         </div>


        <!-- 页脚内容 -->
        <footer>
          <div class="pull-right">
             <a href="" target="_blank" title=""></a> - Collect from <a href="" title="" target="_blank">自动化运维管理平台</a>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /页脚内容 -->

     </div>
    </div>

    <!-- jQuery -->
    <script src="/static/js/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>
{##}
    <!-- FastClick -->
    <script src="/static/js/fastclick.js"></script>
    <!-- NProgress -->
    <script src="/static/js/nprogress.js"></script>
    <!-- Chart.js -->
    <script src="/static/js/Chart.min.js"></script>
    <!-- gauge.js -->
    <script src="/static/js/gauge.min.js"></script>
    <!-- bootstrap-progressbar -->
    <script src="/static/js/bootstrap-progressbar.min.js"></script>
    <!-- iCheck -->
    <script src="/static/js/icheck.min.js"></script>
    <!-- Skycons -->
    <script src="/static/js/skycons.js"></script>
    <!-- Flot -->
    <script src="/static/js/jquery.flot.js"></script>
    <script src="/static/js/jquery.flot.pie.js"></script>
    <script src="/static/js/jquery.flot.time.js"></script>
    <script src="/static/js/jquery.flot.stack.js"></script>
    <script src="/static/js/jquery.flot.resize.js"></script>
    <!-- Flot plugins -->
    <script src="/static/js/jquery.flot.orderBars.js"></script>
    <script src="/static/js/jquery.flot.spline.min.js"></script>
    <script src="/static/js/curvedLines.js"></script>
    <!-- DateJS -->
    <script src="/static/js/date.js"></script>
    <!-- JQVMap -->
    <script src="/static/js/jquery.vmap.js"></script>
    <script src="/static/js/jquery.vmap.world.js"></script>
    <script src="/static/js/jquery.vmap.sampledata.js"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="/static/js/moment.min.js"></script>
    <script src="/static/js/daterangepicker.js"></script>

        <!-- jQuery 3 -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/sweetalert.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/Validform_v5.3.2_min.js' %}"></script>
    <script type="text/javascript" src="{% static 'chosen/chosen.jquery.min.js' %}"></script>

    <!-- Custom Theme Scripts -->
    <script src="{% static 'js/custom.min.js' %}"></script>
    <script src="{% static 'js/select2.js' %}"></script>
    <script src="{% static 'js/i18n/zh-CN.js' %}"></script>

	<script>
            function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }


</script>
<script>
{% block js %}

{% endblock %}
</script>
	
  </body>
</html>

templates/batch_add.html
{% extends 'base.html' %}

{% block content %}

    <div class="container-fluid">
    <div class="row">
        <h2>批量添加解析记录</h2>
    </div>

    <div class="row">
        <div class="col-md-12 ">
            <div class="panel panel-default">
                <br>
                <form class="form-horizontal" method="post" id="batch-dns">
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="inputPassword3" class="col-sm-2 control-label">类型</label>
                        <div class="col-lg-8">
                            <select class="form-control" name="type">
                                  <option value="A">A</option>
                                  <option value="CNAME">CNAME</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="inputPassword3" class="col-sm-2 control-label">域名</label>
                        <div class="col-lg-8">
                            <select class="form-control" name="domain">
                                {% for foo in zone_list %}
                                  <option value="{{ foo.title }}">{{ foo.title }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">输入您的IP地址和解析记录</label>
                        <div class="col-lg-8 ">
                            <textarea class="form-control" rows="9" name="batch" form="batch-dns"></textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <input type="submit" class="btn btn-default" value="提交"></input>
                        </div>
                    </div>

                </form>
                <br>
            </div>

        </div>
    </div>

</div>
{% endblock %}

templates/detail-add.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <h2>添加解析记录—《{{ domain }}》</h2>
        </div>
    </div>

    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <form action="" id="dns_add" method="post" class="form-horizontal"><br>
                        {% csrf_token %}
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">记录类型：</label>
                        <div class="col-sm-9 select">
                            <select id="dns_type" name="type" class="form-control">
                                <option value="A" id="a">A-将域名解析一个IPV4地址</option>
                                <option value="CNAME" id="cname">CNAME-将域名指向另一个域名</option>
                                <option value="NS" id="nx">NS-将子域名指定其他DNS服务器解析</option>
                                <option value="MX" id="mx">MX-将域名指向邮件服务器地址</option>
                                <option value="AAAA" id="aaaa">AAAA-将域名执行一个IPV6地址</option>
                                <option value="TXT" id="txt">TXT-通常做SPF记录(反垃圾邮件)</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">主机记录：</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="inputEmail3" name="host"
                                   value="">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">解析线路：</label>
                        <div class="col-sm-9 select">
                            <select id="dns_type" name="view" class="form-control">
                                <option value="Telecom" id="a">Telecom</option>
                                <option value="Unicom" id="cname">Unicom</option>
                                <option value="CMCC" id="nx">CMCC</option>
                                <option value="other" id="mx">other</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">记录值：</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="inputEmail3" name="data"
                                   value="">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">TTL：</label>
                        <div class="col-sm-9">
                            <input type="number" min="60" class="form-control" id="inputEmail3" name="ttl"
                                   value="60">
                        </div>
                    </div>

                    <div class="form-group hidden" id="in_mx">
                        <label for="in_mx" class="col-sm-2 control-label">MX优先级：</label>
                        <div class="col-sm-9">
                            <input type="number" min="1" class="form-control" name="ipt_mx"
                                   value="10">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <input type="submit" class="btn btn-default" value="提交更改" id="sub"></input>
                        </div>
                    </div>
                    <br>
                </form>

            </div>
        </div>
    </div>

    <script src="/static/jquery-3.3.1.js"></script>
    <script type="application/javascript">

        $('#mx').click(function () {
            $('#in_mx').attr('class', 'show');
        });
        $('#nx').click(function () {
            $('#in_mx').attr('class', 'hidden');
        });
        $('#cname').click(function () {
            $('#in_mx').attr('class', 'hidden');
        });
        $('#a').click(function () {
            $('#in_mx').attr('class', 'hidden');
        });
        $('#txt').click(function () {
            $('#in_mx').attr('class', 'hidden');
        });
        $('#aaaa').click(function () {
            $('#in_mx').attr('class', 'hidden');
        });

    </script>
{% endblock %}

templates/detail_list.html
{% extends "base.html" %}

{% block content %}

    <div class="row">
        <h2 id="t"> {{ domain }} </h2>
    </div>

    <div class="row">
        <a href="/detail-add/{{ domain }}/"><button type="button" class="btn btn-info">添加记录</button></a>
    </div>

    <div class="col-md-12 ">
        <div class="panel panel-default">
            <table class="table table-condensed">
                <tr>
                    <th>记录类型</th>
                    <th>解析线路</th>
                    <th>主机记录</th>
                    <th>记录值</th>
                    <th>MX优先级</th>
                    <th>TTL</th>
                    <th>操作</th>
                </tr>
                {% for zone in dns_list %}
                    {% if zone.type != "SOA" %}
                        <tr>
                            <td>{{ zone.dns_type }}</td>
                            <td>{{ zone.get_view_display }}</td>
                            <td>{{ zone.host }}</td>
                            <td>{{ zone.data }}</td>
                            <td>
                                {% if zone.mx_priority %}
                                    {{ zone.mx_priority }}
                                {% else %}
                                    --
                                {% endif %}
                            </td>
                            <td>{{ zone.ttl }}</td>

                            <td>
                                <a href="/z_info_edit/{{ zone.id }}/">修改</a> |
                                <a href="/z_info_del/{{ zone.id }}/">删除</a>
                            </td>

                        </tr>
                    {% endif %}
                {% endfor %}

            </table>
        </div>
    </div>


{% endblock %}

templates/error.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<script src="{% static 'jquery-3.3.1.js' %} "></script>
{#<link rel="stylesheet" href="http://mishengqiang.com/sweetalert/css/sweetalert.css">#}
<link rel="stylesheet" href="{% static 'css/sweetalert.css' %}">
<link rel="stylesheet" href="{% static 'css/sweet-alert.min.js' %}">
<script src="{% static 'js/sweetalert2.all.min.js' %} "></script>
{#<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>#}
<script src="{% static 'jquery-3.3.1.js' %}"></script>
{#<script src="http://mishengqiang.com/sweetalert/js/sweetalert-dev.js"></script>#}
<script src="{% static 'js/sweet-alert.min.js' %}"></script>
<div>
    {#获取错误信息#}
    <input type="hidden" id="msg" value="{{ msg }}">
    <input type="hidden" id="url" value="{{ url }}">
</div>

<script>
    $(function () {
        var msg = $("#msg").val();
        var url = $("#url").val();
        console.log(msg);
        console.log(url);

        if (msg.length > 0) {  //判断是否有错误信息
            swal({
                title: msg,
                text: "3秒后自动关闭。",
                type: 'error',
                timer: 3000,
                showConfirmButton: false
            }, function () {
                window.location.href = /login/;  //跳转指定url
            });

        }


    })
</script>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Signin Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/signin.css" rel="stylesheet">

  </head>
<body>

    <div class="container">

      <form class="form-signin" method="post">
        <h2 class="form-signin-heading" style="text-align:center";>智能DNS系统</h2>

        <label for="inputEmail" class="sr-only">用户名</label>
        <input type="text" id="inputEmail" class="form-control" required="" autofocus="" placeholder="用户名" name="username">

        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" required="" placeholder="密码" name="password">

        <div class="checkbox hidden">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>

    <div id="extwaiimpotscp" style="display:none" v="{aa90" f="ZTJGaE9UQTVNekkwTFRjMU1qQXROR1JqWkMwNVpXSXdMVGxtTUdFNVpXTXpZekF3TTMwPQ==" q="c54fe6cc" c="113.2" i="117.9" u="23.81" s="19090508" w="false" m="BMe=" vn="yotcn"></div></div> <!-- /container -->



</body>
</html>

templates/zone_add.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <h2>添加域名</h2>
        </div>
    </div>

    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <form action="" id="dns_add" method="post" class="form-horizontal"><br>
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-3 control-label">你的域名：</label>
                        <div class="col-sm-7">
                            <input type="text" class="form-control" id="inputEmail3" name="domain"
                                   value="">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-offset-5 col-sm-10">
                            <input type="submit" class="btn btn-default" value="域名添加" id="sub"></input>
                        </div>
                    </div>
                    <br>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/zone_list.html
{% extends "base.html" %}

{% block content %}

    <style>
        table {
            align: "right",
        }
    </style>

    <div class="row">
        <h2>DNS Zone区域</h2>
    </div>

{#    <div class="row add-zone">#}
{#        <a href="">#}
{#            <button>添加域名</button>#}
{#        </a>#}
{#    </div>#}

    <div class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Modal title</h4>
                </div>
                <div class="modal-body">
                    <p>One fine body&hellip;</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    <div class="row">
        <div class="col-md-12 ">
            <div class="panel panel-default">
                <table class="table table-bordered table-striped dataTable" style="text-align: center">
                    <tr>
                        <th style="text-align:center">ID</th>
                        <th style="text-align:center">Zone域名</th>
{#                        <th>状态</th>#}
                        <th style="text-align:center">操作</th>
                    </tr>

                    {% for zone in zone_list %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td><a href="/detail/{{ zone.title }}/">{{ zone.title }}</a></td>
{#                            <td>#}
{#                                {% if check %}#}
{#                                    <span class="glyphicon glyphicon-ok-circle" aria-hidden="true"#}
{#                                          style="color: lawngreen"></span>#}
{#                                {% else %}#}
{#                                    <span class="glyphicon glyphicon-remove-circle" aria-hidden="true"#}
{#                                          style="color: red"></span>#}
{#                                {% endif %}#}
{#                            </td>#}
                            <td>
                                <a href="/detail/{{ zone.title }}/"><i class="fa fa-cog"></i></a> |
                                <a href="/zone-add/{{ zone.id }}/"><i class="fa fa-times"></i></a>
                            </td>
                        </tr>
                    {% endfor %}

                </table>
            </div>
        </div>
    </div>

{% endblock %}